//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HideezServiceHost.HideezServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceClientParameters", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ServiceClientParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HideezServiceHost.HideezServiceReference.ClientType ClientTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HideezServiceHost.HideezServiceReference.ClientType ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientType", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    public enum ClientType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceHost = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DesktopClient = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestConsole = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoteDeviceConnection = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class HideezServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceDTO", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class DeviceDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte BatteryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Version BootloaderVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanLockPyProximityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FinishedMainFlowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Version FirmwareVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAuthorizedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBootField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCanUnlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsConnectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInitializedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PinAttemptsRemainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ProximityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint StorageFreeSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint StorageTotalSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnlockAttemptsRemainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte Battery {
            get {
                return this.BatteryField;
            }
            set {
                if ((this.BatteryField.Equals(value) != true)) {
                    this.BatteryField = value;
                    this.RaisePropertyChanged("Battery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Version BootloaderVersion {
            get {
                return this.BootloaderVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.BootloaderVersionField, value) != true)) {
                    this.BootloaderVersionField = value;
                    this.RaisePropertyChanged("BootloaderVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanLockPyProximity {
            get {
                return this.CanLockPyProximityField;
            }
            set {
                if ((this.CanLockPyProximityField.Equals(value) != true)) {
                    this.CanLockPyProximityField = value;
                    this.RaisePropertyChanged("CanLockPyProximity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FinishedMainFlow {
            get {
                return this.FinishedMainFlowField;
            }
            set {
                if ((this.FinishedMainFlowField.Equals(value) != true)) {
                    this.FinishedMainFlowField = value;
                    this.RaisePropertyChanged("FinishedMainFlow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Version FirmwareVersion {
            get {
                return this.FirmwareVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmwareVersionField, value) != true)) {
                    this.FirmwareVersionField = value;
                    this.RaisePropertyChanged("FirmwareVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAuthorized {
            get {
                return this.IsAuthorizedField;
            }
            set {
                if ((this.IsAuthorizedField.Equals(value) != true)) {
                    this.IsAuthorizedField = value;
                    this.RaisePropertyChanged("IsAuthorized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBoot {
            get {
                return this.IsBootField;
            }
            set {
                if ((this.IsBootField.Equals(value) != true)) {
                    this.IsBootField = value;
                    this.RaisePropertyChanged("IsBoot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCanUnlock {
            get {
                return this.IsCanUnlockField;
            }
            set {
                if ((this.IsCanUnlockField.Equals(value) != true)) {
                    this.IsCanUnlockField = value;
                    this.RaisePropertyChanged("IsCanUnlock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConnected {
            get {
                return this.IsConnectedField;
            }
            set {
                if ((this.IsConnectedField.Equals(value) != true)) {
                    this.IsConnectedField = value;
                    this.RaisePropertyChanged("IsConnected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInitialized {
            get {
                return this.IsInitializedField;
            }
            set {
                if ((this.IsInitializedField.Equals(value) != true)) {
                    this.IsInitializedField = value;
                    this.RaisePropertyChanged("IsInitialized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerEmail {
            get {
                return this.OwnerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerEmailField, value) != true)) {
                    this.OwnerEmailField = value;
                    this.RaisePropertyChanged("OwnerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PinAttemptsRemain {
            get {
                return this.PinAttemptsRemainField;
            }
            set {
                if ((this.PinAttemptsRemainField.Equals(value) != true)) {
                    this.PinAttemptsRemainField = value;
                    this.RaisePropertyChanged("PinAttemptsRemain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Proximity {
            get {
                return this.ProximityField;
            }
            set {
                if ((this.ProximityField.Equals(value) != true)) {
                    this.ProximityField = value;
                    this.RaisePropertyChanged("Proximity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNo {
            get {
                return this.SerialNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNoField, value) != true)) {
                    this.SerialNoField = value;
                    this.RaisePropertyChanged("SerialNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint StorageFreeSize {
            get {
                return this.StorageFreeSizeField;
            }
            set {
                if ((this.StorageFreeSizeField.Equals(value) != true)) {
                    this.StorageFreeSizeField = value;
                    this.RaisePropertyChanged("StorageFreeSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint StorageTotalSize {
            get {
                return this.StorageTotalSizeField;
            }
            set {
                if ((this.StorageTotalSizeField.Equals(value) != true)) {
                    this.StorageTotalSizeField = value;
                    this.RaisePropertyChanged("StorageTotalSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnlockAttemptsRemain {
            get {
                return this.UnlockAttemptsRemainField;
            }
            set {
                if ((this.UnlockAttemptsRemainField.Equals(value) != true)) {
                    this.UnlockAttemptsRemainField = value;
                    this.RaisePropertyChanged("UnlockAttemptsRemain");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkstationEventDTO", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class WorkstationEventDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeverityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountLogin {
            get {
                return this.AccountLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountLoginField, value) != true)) {
                    this.AccountLoginField = value;
                    this.RaisePropertyChanged("AccountLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProximitySettingsDTO", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ProximitySettingsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowEditProximitySettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LockProximityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnlockProximityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowEditProximitySettings {
            get {
                return this.AllowEditProximitySettingsField;
            }
            set {
                if ((this.AllowEditProximitySettingsField.Equals(value) != true)) {
                    this.AllowEditProximitySettingsField = value;
                    this.RaisePropertyChanged("AllowEditProximitySettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LockProximity {
            get {
                return this.LockProximityField;
            }
            set {
                if ((this.LockProximityField.Equals(value) != true)) {
                    this.LockProximityField = value;
                    this.RaisePropertyChanged("LockProximity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mac {
            get {
                return this.MacField;
            }
            set {
                if ((object.ReferenceEquals(this.MacField, value) != true)) {
                    this.MacField = value;
                    this.RaisePropertyChanged("Mac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNo {
            get {
                return this.SerialNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNoField, value) != true)) {
                    this.SerialNoField = value;
                    this.RaisePropertyChanged("SerialNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnlockProximity {
            get {
                return this.UnlockProximityField;
            }
            set {
                if ((this.UnlockProximityField.Equals(value) != true)) {
                    this.UnlockProximityField = value;
                    this.RaisePropertyChanged("UnlockProximity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HesStatus", Namespace="http://schemas.datacontract.org/2004/07/HideezMiddleware")]
    public enum HesStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HesNotConnected = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotApproved = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RfidStatus", Namespace="http://schemas.datacontract.org/2004/07/HideezMiddleware")]
    public enum RfidStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RfidServiceNotConnected = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RfidReaderNotConnected = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BluetoothStatus", Namespace="http://schemas.datacontract.org/2004/07/HideezMiddleware")]
    public enum BluetoothStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Resetting = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unsupported = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unauthorized = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PoweredOff = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceStateDTO", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class DeviceStateDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HideezServiceHost.HideezServiceReference.AccessLevelDTO AccessLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte BatteryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HideezServiceHost.HideezServiceReference.ButtonPressCode ButtonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte OtherConnectionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PinAttemptsRemainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte RssiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StorageUpdateCounterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HideezServiceHost.HideezServiceReference.AccessLevelDTO AccessLevel {
            get {
                return this.AccessLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessLevelField, value) != true)) {
                    this.AccessLevelField = value;
                    this.RaisePropertyChanged("AccessLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte Battery {
            get {
                return this.BatteryField;
            }
            set {
                if ((this.BatteryField.Equals(value) != true)) {
                    this.BatteryField = value;
                    this.RaisePropertyChanged("Battery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HideezServiceHost.HideezServiceReference.ButtonPressCode Button {
            get {
                return this.ButtonField;
            }
            set {
                if ((this.ButtonField.Equals(value) != true)) {
                    this.ButtonField = value;
                    this.RaisePropertyChanged("Button");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte OtherConnections {
            get {
                return this.OtherConnectionsField;
            }
            set {
                if ((this.OtherConnectionsField.Equals(value) != true)) {
                    this.OtherConnectionsField = value;
                    this.RaisePropertyChanged("OtherConnections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PinAttemptsRemain {
            get {
                return this.PinAttemptsRemainField;
            }
            set {
                if ((this.PinAttemptsRemainField.Equals(value) != true)) {
                    this.PinAttemptsRemainField = value;
                    this.RaisePropertyChanged("PinAttemptsRemain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte Rssi {
            get {
                return this.RssiField;
            }
            set {
                if ((this.RssiField.Equals(value) != true)) {
                    this.RssiField = value;
                    this.RaisePropertyChanged("Rssi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte StorageUpdateCounter {
            get {
                return this.StorageUpdateCounterField;
            }
            set {
                if ((this.StorageUpdateCounterField.Equals(value) != true)) {
                    this.StorageUpdateCounterField = value;
                    this.RaisePropertyChanged("StorageUpdateCounter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessLevelDTO", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class AccessLevelDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsButtonRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLinkRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMasterKeyRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNewPinRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPinRequiredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsButtonRequired {
            get {
                return this.IsButtonRequiredField;
            }
            set {
                if ((this.IsButtonRequiredField.Equals(value) != true)) {
                    this.IsButtonRequiredField = value;
                    this.RaisePropertyChanged("IsButtonRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLinkRequired {
            get {
                return this.IsLinkRequiredField;
            }
            set {
                if ((this.IsLinkRequiredField.Equals(value) != true)) {
                    this.IsLinkRequiredField = value;
                    this.RaisePropertyChanged("IsLinkRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocked {
            get {
                return this.IsLockedField;
            }
            set {
                if ((this.IsLockedField.Equals(value) != true)) {
                    this.IsLockedField = value;
                    this.RaisePropertyChanged("IsLocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMasterKeyRequired {
            get {
                return this.IsMasterKeyRequiredField;
            }
            set {
                if ((this.IsMasterKeyRequiredField.Equals(value) != true)) {
                    this.IsMasterKeyRequiredField = value;
                    this.RaisePropertyChanged("IsMasterKeyRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNewPinRequired {
            get {
                return this.IsNewPinRequiredField;
            }
            set {
                if ((this.IsNewPinRequiredField.Equals(value) != true)) {
                    this.IsNewPinRequiredField = value;
                    this.RaisePropertyChanged("IsNewPinRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPinRequired {
            get {
                return this.IsPinRequiredField;
            }
            set {
                if ((this.IsPinRequiredField.Equals(value) != true)) {
                    this.IsPinRequiredField = value;
                    this.RaisePropertyChanged("IsPinRequired");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ButtonPressCode", Namespace="http://schemas.datacontract.org/2004/07/Hideez.SDK.Communication")]
    public enum ButtonPressCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Triple = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quad = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Penta = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hexa = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hepta = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Octa = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Multi = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Long = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuperLong = 17,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HideezServiceReference.IHideezService", CallbackContract=typeof(HideezServiceHost.HideezServiceReference.IHideezServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IHideezService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/AttachClient", ReplyAction="http://tempuri.org/IHideezService/AttachClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/AttachClientHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        bool AttachClient(HideezServiceHost.HideezServiceReference.ServiceClientParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/AttachClient", ReplyAction="http://tempuri.org/IHideezService/AttachClientResponse")]
        System.Threading.Tasks.Task<bool> AttachClientAsync(HideezServiceHost.HideezServiceReference.ServiceClientParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/DetachClient", ReplyAction="http://tempuri.org/IHideezService/DetachClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/DetachClientHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void DetachClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/DetachClient", ReplyAction="http://tempuri.org/IHideezService/DetachClientResponse")]
        System.Threading.Tasks.Task DetachClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/Ping", ReplyAction="http://tempuri.org/IHideezService/PingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/PingHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        int Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/Ping", ReplyAction="http://tempuri.org/IHideezService/PingResponse")]
        System.Threading.Tasks.Task<int> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/Shutdown", ReplyAction="http://tempuri.org/IHideezService/ShutdownResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/ShutdownHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void Shutdown();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/Shutdown", ReplyAction="http://tempuri.org/IHideezService/ShutdownResponse")]
        System.Threading.Tasks.Task ShutdownAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetDevices", ReplyAction="http://tempuri.org/IHideezService/GetDevicesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/GetDevicesHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        HideezServiceHost.HideezServiceReference.DeviceDTO[] GetDevices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetDevices", ReplyAction="http://tempuri.org/IHideezService/GetDevicesResponse")]
        System.Threading.Tasks.Task<HideezServiceHost.HideezServiceReference.DeviceDTO[]> GetDevicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetAvailableChannels", ReplyAction="http://tempuri.org/IHideezService/GetAvailableChannelsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/GetAvailableChannelsHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        byte[] GetAvailableChannels(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetAvailableChannels", ReplyAction="http://tempuri.org/IHideezService/GetAvailableChannelsResponse")]
        System.Threading.Tasks.Task<byte[]> GetAvailableChannelsAsync(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/DisconnectDevice", ReplyAction="http://tempuri.org/IHideezService/DisconnectDeviceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/DisconnectDeviceHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void DisconnectDevice(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/DisconnectDevice", ReplyAction="http://tempuri.org/IHideezService/DisconnectDeviceResponse")]
        System.Threading.Tasks.Task DisconnectDeviceAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoveDevice", ReplyAction="http://tempuri.org/IHideezService/RemoveDeviceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/RemoveDeviceHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void RemoveDevice(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoveDevice", ReplyAction="http://tempuri.org/IHideezService/RemoveDeviceResponse")]
        System.Threading.Tasks.Task RemoveDeviceAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/EstablishRemoteDeviceConnection", ReplyAction="http://tempuri.org/IHideezService/EstablishRemoteDeviceConnectionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/EstablishRemoteDeviceConnectionHideezServiceFau" +
            "ltFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        string EstablishRemoteDeviceConnection(string serialNo, byte channelNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/EstablishRemoteDeviceConnection", ReplyAction="http://tempuri.org/IHideezService/EstablishRemoteDeviceConnectionResponse")]
        System.Threading.Tasks.Task<string> EstablishRemoteDeviceConnectionAsync(string serialNo, byte channelNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_VerifyCommand", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_VerifyCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/RemoteConnection_VerifyCommandHideezServiceFaul" +
            "tFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        byte[] RemoteConnection_VerifyCommand(string connectionId, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_VerifyCommand", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_VerifyCommandResponse")]
        System.Threading.Tasks.Task<byte[]> RemoteConnection_VerifyCommandAsync(string connectionId, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_RemoteCommand", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_RemoteCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/RemoteConnection_RemoteCommandHideezServiceFaul" +
            "tFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        byte[] RemoteConnection_RemoteCommand(string connectionId, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_RemoteCommand", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_RemoteCommandResponse")]
        System.Threading.Tasks.Task<byte[]> RemoteConnection_RemoteCommandAsync(string connectionId, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_ResetChannel", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_ResetChannelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/RemoteConnection_ResetChannelHideezServiceFault" +
            "Fault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void RemoteConnection_ResetChannel(string connectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_ResetChannel", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_ResetChannelResponse")]
        System.Threading.Tasks.Task RemoteConnection_ResetChannelAsync(string connectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/PublishEvent", ReplyAction="http://tempuri.org/IHideezService/PublishEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/PublishEventHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void PublishEvent(HideezServiceHost.HideezServiceReference.WorkstationEventDTO workstationEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/PublishEvent", ReplyAction="http://tempuri.org/IHideezService/PublishEventResponse")]
        System.Threading.Tasks.Task PublishEventAsync(HideezServiceHost.HideezServiceReference.WorkstationEventDTO workstationEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SendPin", ReplyAction="http://tempuri.org/IHideezService/SendPinResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/SendPinHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void SendPin(string deviceId, byte[] pin, byte[] oldPin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SendPin", ReplyAction="http://tempuri.org/IHideezService/SendPinResponse")]
        System.Threading.Tasks.Task SendPinAsync(string deviceId, byte[] pin, byte[] oldPin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/CancelPin", ReplyAction="http://tempuri.org/IHideezService/CancelPinResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/CancelPinHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void CancelPin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/CancelPin", ReplyAction="http://tempuri.org/IHideezService/CancelPinResponse")]
        System.Threading.Tasks.Task CancelPinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SendActivationCode", ReplyAction="http://tempuri.org/IHideezService/SendActivationCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/SendActivationCodeHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void SendActivationCode(string deviceId, byte[] activationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SendActivationCode", ReplyAction="http://tempuri.org/IHideezService/SendActivationCodeResponse")]
        System.Threading.Tasks.Task SendActivationCodeAsync(string deviceId, byte[] activationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/CancelActivationCode", ReplyAction="http://tempuri.org/IHideezService/CancelActivationCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/CancelActivationCodeHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void CancelActivationCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/CancelActivationCode", ReplyAction="http://tempuri.org/IHideezService/CancelActivationCodeResponse")]
        System.Threading.Tasks.Task CancelActivationCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SetProximitySettings", ReplyAction="http://tempuri.org/IHideezService/SetProximitySettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/SetProximitySettingsHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void SetProximitySettings(string mac, int lockProximity, int unlockProximity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SetProximitySettings", ReplyAction="http://tempuri.org/IHideezService/SetProximitySettingsResponse")]
        System.Threading.Tasks.Task SetProximitySettingsAsync(string mac, int lockProximity, int unlockProximity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetCurrentProximitySettings", ReplyAction="http://tempuri.org/IHideezService/GetCurrentProximitySettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/GetCurrentProximitySettingsHideezServiceFaultFa" +
            "ult", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        HideezServiceHost.HideezServiceReference.ProximitySettingsDTO GetCurrentProximitySettings(string mac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetCurrentProximitySettings", ReplyAction="http://tempuri.org/IHideezService/GetCurrentProximitySettingsResponse")]
        System.Threading.Tasks.Task<HideezServiceHost.HideezServiceReference.ProximitySettingsDTO> GetCurrentProximitySettingsAsync(string mac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetServerAddress", ReplyAction="http://tempuri.org/IHideezService/GetServerAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/GetServerAddressHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        string GetServerAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetServerAddress", ReplyAction="http://tempuri.org/IHideezService/GetServerAddressResponse")]
        System.Threading.Tasks.Task<string> GetServerAddressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/ChangeServerAddress", ReplyAction="http://tempuri.org/IHideezService/ChangeServerAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/ChangeServerAddressHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        bool ChangeServerAddress(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/ChangeServerAddress", ReplyAction="http://tempuri.org/IHideezService/ChangeServerAddressResponse")]
        System.Threading.Tasks.Task<bool> ChangeServerAddressAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/IsSoftwareVaultUnlockModuleEnabled", ReplyAction="http://tempuri.org/IHideezService/IsSoftwareVaultUnlockModuleEnabledResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/IsSoftwareVaultUnlockModuleEnabledHideezService" +
            "FaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        bool IsSoftwareVaultUnlockModuleEnabled();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/IsSoftwareVaultUnlockModuleEnabled", ReplyAction="http://tempuri.org/IHideezService/IsSoftwareVaultUnlockModuleEnabledResponse")]
        System.Threading.Tasks.Task<bool> IsSoftwareVaultUnlockModuleEnabledAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SetSoftwareVaultUnlockModuleState", ReplyAction="http://tempuri.org/IHideezService/SetSoftwareVaultUnlockModuleStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezServiceHost.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/SetSoftwareVaultUnlockModuleStateHideezServiceF" +
            "aultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void SetSoftwareVaultUnlockModuleState(bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SetSoftwareVaultUnlockModuleState", ReplyAction="http://tempuri.org/IHideezService/SetSoftwareVaultUnlockModuleStateResponse")]
        System.Threading.Tasks.Task SetSoftwareVaultUnlockModuleStateAsync(bool enabled);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHideezServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/ProximitySettingsChanged")]
        void ProximitySettingsChanged();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/LockWorkstationRequest")]
        void LockWorkstationRequest();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/ActivateWorkstationScreenRequest")]
        void ActivateWorkstationScreenRequest();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/ServiceComponentsStateChanged")]
        void ServiceComponentsStateChanged(HideezServiceHost.HideezServiceReference.HesStatus hesStatus, HideezServiceHost.HideezServiceReference.RfidStatus rfidStatus, HideezServiceHost.HideezServiceReference.BluetoothStatus bluetoothStatus, HideezServiceHost.HideezServiceReference.HesStatus tbHesStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/ServiceNotificationReceived")]
        void ServiceNotificationReceived(string message, string notificationId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/ServiceErrorReceived")]
        void ServiceErrorReceived(string error, string notificationId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/DevicesCollectionChanged")]
        void DevicesCollectionChanged(HideezServiceHost.HideezServiceReference.DeviceDTO[] devices);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/DeviceConnectionStateChanged")]
        void DeviceConnectionStateChanged(HideezServiceHost.HideezServiceReference.DeviceDTO device);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/DeviceInitialized")]
        void DeviceInitialized(HideezServiceHost.HideezServiceReference.DeviceDTO device);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/DeviceFinishedMainFlow")]
        void DeviceFinishedMainFlow(HideezServiceHost.HideezServiceReference.DeviceDTO device);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/DeviceOperationCancelled")]
        void DeviceOperationCancelled(HideezServiceHost.HideezServiceReference.DeviceDTO device);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/DeviceProximityChanged")]
        void DeviceProximityChanged(string deviceId, double proximity);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/DeviceBatteryChanged")]
        void DeviceBatteryChanged(string deviceId, int battery);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/DeviceProximityLockEnabled")]
        void DeviceProximityLockEnabled(HideezServiceHost.HideezServiceReference.DeviceDTO device);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/RemoteConnection_DeviceStateChanged")]
        void RemoteConnection_DeviceStateChanged(string deviceId, HideezServiceHost.HideezServiceReference.DeviceStateDTO stateDto);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/ShowPinUi")]
        void ShowPinUi(string deviceId, bool withConfirm, bool askOldPin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/ShowButtonConfirmUi")]
        void ShowButtonConfirmUi(string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/HidePinUi")]
        void HidePinUi();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/ShowActivationCodeUi")]
        void ShowActivationCodeUi(string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHideezService/HideActivationCodeUi")]
        void HideActivationCodeUi();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHideezServiceChannel : HideezServiceHost.HideezServiceReference.IHideezService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HideezServiceClient : System.ServiceModel.DuplexClientBase<HideezServiceHost.HideezServiceReference.IHideezService>, HideezServiceHost.HideezServiceReference.IHideezService {
        
        public HideezServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public HideezServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public HideezServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public HideezServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public HideezServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool AttachClient(HideezServiceHost.HideezServiceReference.ServiceClientParameters parameters) {
            return base.Channel.AttachClient(parameters);
        }
        
        public System.Threading.Tasks.Task<bool> AttachClientAsync(HideezServiceHost.HideezServiceReference.ServiceClientParameters parameters) {
            return base.Channel.AttachClientAsync(parameters);
        }
        
        public void DetachClient() {
            base.Channel.DetachClient();
        }
        
        public System.Threading.Tasks.Task DetachClientAsync() {
            return base.Channel.DetachClientAsync();
        }
        
        public int Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<int> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public void Shutdown() {
            base.Channel.Shutdown();
        }
        
        public System.Threading.Tasks.Task ShutdownAsync() {
            return base.Channel.ShutdownAsync();
        }
        
        public HideezServiceHost.HideezServiceReference.DeviceDTO[] GetDevices() {
            return base.Channel.GetDevices();
        }
        
        public System.Threading.Tasks.Task<HideezServiceHost.HideezServiceReference.DeviceDTO[]> GetDevicesAsync() {
            return base.Channel.GetDevicesAsync();
        }
        
        public byte[] GetAvailableChannels(string serialNo) {
            return base.Channel.GetAvailableChannels(serialNo);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetAvailableChannelsAsync(string serialNo) {
            return base.Channel.GetAvailableChannelsAsync(serialNo);
        }
        
        public void DisconnectDevice(string id) {
            base.Channel.DisconnectDevice(id);
        }
        
        public System.Threading.Tasks.Task DisconnectDeviceAsync(string id) {
            return base.Channel.DisconnectDeviceAsync(id);
        }
        
        public void RemoveDevice(string id) {
            base.Channel.RemoveDevice(id);
        }
        
        public System.Threading.Tasks.Task RemoveDeviceAsync(string id) {
            return base.Channel.RemoveDeviceAsync(id);
        }
        
        public string EstablishRemoteDeviceConnection(string serialNo, byte channelNo) {
            return base.Channel.EstablishRemoteDeviceConnection(serialNo, channelNo);
        }
        
        public System.Threading.Tasks.Task<string> EstablishRemoteDeviceConnectionAsync(string serialNo, byte channelNo) {
            return base.Channel.EstablishRemoteDeviceConnectionAsync(serialNo, channelNo);
        }
        
        public byte[] RemoteConnection_VerifyCommand(string connectionId, byte[] data) {
            return base.Channel.RemoteConnection_VerifyCommand(connectionId, data);
        }
        
        public System.Threading.Tasks.Task<byte[]> RemoteConnection_VerifyCommandAsync(string connectionId, byte[] data) {
            return base.Channel.RemoteConnection_VerifyCommandAsync(connectionId, data);
        }
        
        public byte[] RemoteConnection_RemoteCommand(string connectionId, byte[] data) {
            return base.Channel.RemoteConnection_RemoteCommand(connectionId, data);
        }
        
        public System.Threading.Tasks.Task<byte[]> RemoteConnection_RemoteCommandAsync(string connectionId, byte[] data) {
            return base.Channel.RemoteConnection_RemoteCommandAsync(connectionId, data);
        }
        
        public void RemoteConnection_ResetChannel(string connectionId) {
            base.Channel.RemoteConnection_ResetChannel(connectionId);
        }
        
        public System.Threading.Tasks.Task RemoteConnection_ResetChannelAsync(string connectionId) {
            return base.Channel.RemoteConnection_ResetChannelAsync(connectionId);
        }
        
        public void PublishEvent(HideezServiceHost.HideezServiceReference.WorkstationEventDTO workstationEvent) {
            base.Channel.PublishEvent(workstationEvent);
        }
        
        public System.Threading.Tasks.Task PublishEventAsync(HideezServiceHost.HideezServiceReference.WorkstationEventDTO workstationEvent) {
            return base.Channel.PublishEventAsync(workstationEvent);
        }
        
        public void SendPin(string deviceId, byte[] pin, byte[] oldPin) {
            base.Channel.SendPin(deviceId, pin, oldPin);
        }
        
        public System.Threading.Tasks.Task SendPinAsync(string deviceId, byte[] pin, byte[] oldPin) {
            return base.Channel.SendPinAsync(deviceId, pin, oldPin);
        }
        
        public void CancelPin() {
            base.Channel.CancelPin();
        }
        
        public System.Threading.Tasks.Task CancelPinAsync() {
            return base.Channel.CancelPinAsync();
        }
        
        public void SendActivationCode(string deviceId, byte[] activationCode) {
            base.Channel.SendActivationCode(deviceId, activationCode);
        }
        
        public System.Threading.Tasks.Task SendActivationCodeAsync(string deviceId, byte[] activationCode) {
            return base.Channel.SendActivationCodeAsync(deviceId, activationCode);
        }
        
        public void CancelActivationCode() {
            base.Channel.CancelActivationCode();
        }
        
        public System.Threading.Tasks.Task CancelActivationCodeAsync() {
            return base.Channel.CancelActivationCodeAsync();
        }
        
        public void SetProximitySettings(string mac, int lockProximity, int unlockProximity) {
            base.Channel.SetProximitySettings(mac, lockProximity, unlockProximity);
        }
        
        public System.Threading.Tasks.Task SetProximitySettingsAsync(string mac, int lockProximity, int unlockProximity) {
            return base.Channel.SetProximitySettingsAsync(mac, lockProximity, unlockProximity);
        }
        
        public HideezServiceHost.HideezServiceReference.ProximitySettingsDTO GetCurrentProximitySettings(string mac) {
            return base.Channel.GetCurrentProximitySettings(mac);
        }
        
        public System.Threading.Tasks.Task<HideezServiceHost.HideezServiceReference.ProximitySettingsDTO> GetCurrentProximitySettingsAsync(string mac) {
            return base.Channel.GetCurrentProximitySettingsAsync(mac);
        }
        
        public string GetServerAddress() {
            return base.Channel.GetServerAddress();
        }
        
        public System.Threading.Tasks.Task<string> GetServerAddressAsync() {
            return base.Channel.GetServerAddressAsync();
        }
        
        public bool ChangeServerAddress(string address) {
            return base.Channel.ChangeServerAddress(address);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeServerAddressAsync(string address) {
            return base.Channel.ChangeServerAddressAsync(address);
        }
        
        public bool IsSoftwareVaultUnlockModuleEnabled() {
            return base.Channel.IsSoftwareVaultUnlockModuleEnabled();
        }
        
        public System.Threading.Tasks.Task<bool> IsSoftwareVaultUnlockModuleEnabledAsync() {
            return base.Channel.IsSoftwareVaultUnlockModuleEnabledAsync();
        }
        
        public void SetSoftwareVaultUnlockModuleState(bool enabled) {
            base.Channel.SetSoftwareVaultUnlockModuleState(enabled);
        }
        
        public System.Threading.Tasks.Task SetSoftwareVaultUnlockModuleStateAsync(bool enabled) {
            return base.Channel.SetSoftwareVaultUnlockModuleStateAsync(enabled);
        }
    }
}
