//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HideezSafe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HideezSafe.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new device ....
        /// </summary>
        internal static string Menu_AddDevice {
            get {
                return ResourceManager.GetString("Menu.AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account password.
        /// </summary>
        internal static string Menu_ChangePassword {
            get {
                return ResourceManager.GetString("Menu.ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string Menu_CheckForUpdates {
            get {
                return ResourceManager.GetString("Menu.CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Menu_InterfaceLanguages {
            get {
                return ResourceManager.GetString("Menu.InterfaceLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch on computer startup.
        /// </summary>
        internal static string Menu_LaunchOnStartup {
            get {
                return ResourceManager.GetString("Menu.LaunchOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal information.
        /// </summary>
        internal static string Menu_Legal {
            get {
                return ResourceManager.GetString("Menu.Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live chat.
        /// </summary>
        internal static string Menu_LiveChat {
            get {
                return ResourceManager.GetString("Menu.LiveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string Menu_LogOff {
            get {
                return ResourceManager.GetString("Menu.LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID usage.
        /// </summary>
        internal static string Menu_RFIDUsage {
            get {
                return ResourceManager.GetString("Menu.RFIDUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hideez Safe.
        /// </summary>
        internal static string Menu_ShowWindow {
            get {
                return ResourceManager.GetString("Menu.ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical support.
        /// </summary>
        internal static string Menu_TechnicalSupport {
            get {
                return ResourceManager.GetString("Menu.TechnicalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User manual.
        /// </summary>
        internal static string Menu_UserManual {
            get {
                return ResourceManager.GetString("Menu.UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video tutorial.
        /// </summary>
        internal static string Menu_VideoTutorial {
            get {
                return ResourceManager.GetString("Menu.VideoTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hideez.com/404.
        /// </summary>
        internal static string Url_Legal {
            get {
                return ResourceManager.GetString("Url.Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hideez.com/404.
        /// </summary>
        internal static string Url_LiveChat {
            get {
                return ResourceManager.GetString("Url.LiveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hideez.com/404.
        /// </summary>
        internal static string Url_RFIDUsage {
            get {
                return ResourceManager.GetString("Url.RFIDUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hideez.com/404.
        /// </summary>
        internal static string Url_UserManual {
            get {
                return ResourceManager.GetString("Url.UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hideez.com/404.
        /// </summary>
        internal static string Url_VideoTutorial {
            get {
                return ResourceManager.GetString("Url.VideoTutorial", resourceCulture);
            }
        }
    }
}
