//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HideezSafe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HideezSafe.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Button_ChangePassword {
            get {
                return ResourceManager.GetString("Button.ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Locker.
        /// </summary>
        internal static string Button_ComputerLocker {
            get {
                return ResourceManager.GetString("Button.ComputerLocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Button_Done {
            get {
                return ResourceManager.GetString("Button.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock/unlock distance Bluetooth.
        /// </summary>
        internal static string Button_LockDistance {
            get {
                return ResourceManager.GetString("Button.LockDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Button_Next {
            get {
                return ResourceManager.GetString("Button.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hideez key.
        /// </summary>
        internal static string DeviceType_Key {
            get {
                return ResourceManager.GetString("DeviceType.Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must be the same as your current system password.
        /// </summary>
        internal static string Dialog_ChangePass_Info {
            get {
                return ResourceManager.GetString("Dialog.ChangePass.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Pass.
        /// </summary>
        internal static string Dialog_ChangePass_New {
            get {
                return ResourceManager.GetString("Dialog.ChangePass.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error save credential..
        /// </summary>
        internal static string Error_SaveCredential {
            get {
                return ResourceManager.GetString("Error.SaveCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device.
        /// </summary>
        internal static string Expander_NoDevice {
            get {
                return ResourceManager.GetString("Expander.NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is not connected.
        /// </summary>
        internal static string Icon_DeviceNotConnected {
            get {
                return ResourceManager.GetString("Icon.DeviceNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Hideez service.
        /// </summary>
        internal static string Icon_FailedConnectHideezService {
            get {
                return ResourceManager.GetString("Icon.FailedConnectHideezService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New notifications are available.
        /// </summary>
        internal static string Icon_NewNotificationsAvailable {
            get {
                return ResourceManager.GetString("Icon.NewNotificationsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New notifications are available
        ///Device is not connected.
        /// </summary>
        internal static string Icon_NoKeyConnectionAlert {
            get {
                return ResourceManager.GetString("Icon.NoKeyConnectionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization in progress.
        /// </summary>
        internal static string Icon_SynchronizationInProgress {
            get {
                return ResourceManager.GetString("Icon.SynchronizationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Label_Login {
            get {
                return ResourceManager.GetString("Label.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock and unlock the computer with a key or phone.                  Watch the video.
        /// </summary>
        internal static string LockPage_Description {
            get {
                return ResourceManager.GetString("LockPage.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control your computer from anywhere.
        /// </summary>
        internal static string LockPage_Header {
            get {
                return ResourceManager.GetString("LockPage.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your password for login into the system.
        /// </summary>
        internal static string LockPage_PasswordInfo {
            get {
                return ResourceManager.GetString("LockPage.PasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password from PC.
        /// </summary>
        internal static string LockPage_PasswordLabel {
            get {
                return ResourceManager.GetString("LockPage.PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 meter.
        /// </summary>
        internal static string LockSettingsPage_OneMeter {
            get {
                return ResourceManager.GetString("LockSettingsPage.OneMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 meters.
        /// </summary>
        internal static string LockSettingsPage_TenMeters {
            get {
                return ResourceManager.GetString("LockSettingsPage.TenMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock distance: .
        /// </summary>
        internal static string LockSettingsPage_UnlockDistans {
            get {
                return ResourceManager.GetString("LockSettingsPage.UnlockDistans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new device ....
        /// </summary>
        internal static string Menu_AddDevice {
            get {
                return ResourceManager.GetString("Menu.AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account password.
        /// </summary>
        internal static string Menu_ChangePassword {
            get {
                return ResourceManager.GetString("Menu.ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string Menu_CheckForUpdates {
            get {
                return ResourceManager.GetString("Menu.CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Menu_InterfaceLanguages {
            get {
                return ResourceManager.GetString("Menu.InterfaceLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch on computer startup.
        /// </summary>
        internal static string Menu_LaunchOnStartup {
            get {
                return ResourceManager.GetString("Menu.LaunchOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal information.
        /// </summary>
        internal static string Menu_Legal {
            get {
                return ResourceManager.GetString("Menu.Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live chat.
        /// </summary>
        internal static string Menu_LiveChat {
            get {
                return ResourceManager.GetString("Menu.LiveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string Menu_LogOff {
            get {
                return ResourceManager.GetString("Menu.LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID usage.
        /// </summary>
        internal static string Menu_RFIDUsage {
            get {
                return ResourceManager.GetString("Menu.RFIDUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hideez Safe.
        /// </summary>
        internal static string Menu_ShowWindow {
            get {
                return ResourceManager.GetString("Menu.ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical support.
        /// </summary>
        internal static string Menu_TechnicalSupport {
            get {
                return ResourceManager.GetString("Menu.TechnicalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User manual.
        /// </summary>
        internal static string Menu_UserManual {
            get {
                return ResourceManager.GetString("Menu.UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video tutorial.
        /// </summary>
        internal static string Menu_VideoTutorial {
            get {
                return ResourceManager.GetString("Menu.VideoTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dongle.
        /// </summary>
        internal static string Status_Dongle {
            get {
                return ResourceManager.GetString("Status.Dongle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HES.
        /// </summary>
        internal static string Status_HES {
            get {
                return ResourceManager.GetString("Status.HES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID.
        /// </summary>
        internal static string Status_RFID {
            get {
                return ResourceManager.GetString("Status.RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Status_Service {
            get {
                return ResourceManager.GetString("Status.Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hideez Dongle connected.
        /// </summary>
        internal static string Status_Tooltip_ConectedDongle {
            get {
                return ResourceManager.GetString("Status.Tooltip.ConectedDongle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to the server.
        /// </summary>
        internal static string Status_Tooltip_ConectedHES {
            get {
                return ResourceManager.GetString("Status.Tooltip.ConectedHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID reader connected.
        /// </summary>
        internal static string Status_Tooltip_ConectedRFID {
            get {
                return ResourceManager.GetString("Status.Tooltip.ConectedRFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to the service.
        /// </summary>
        internal static string Status_Tooltip_ConectedService {
            get {
                return ResourceManager.GetString("Status.Tooltip.ConectedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hideez Dongle disconnected.
        /// </summary>
        internal static string Status_Tooltip_DisconectedDongle {
            get {
                return ResourceManager.GetString("Status.Tooltip.DisconectedDongle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to the server.
        /// </summary>
        internal static string Status_Tooltip_DisconectedHES {
            get {
                return ResourceManager.GetString("Status.Tooltip.DisconectedHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID reader disconnected.
        /// </summary>
        internal static string Status_Tooltip_DisconectedRFID {
            get {
                return ResourceManager.GetString("Status.Tooltip.DisconectedRFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to the service.
        /// </summary>
        internal static string Status_Tooltip_DisconectedService {
            get {
                return ResourceManager.GetString("Status.Tooltip.DisconectedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hideez.com/404.
        /// </summary>
        internal static string Url_Legal {
            get {
                return ResourceManager.GetString("Url.Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hideez.com/404.
        /// </summary>
        internal static string Url_LiveChat {
            get {
                return ResourceManager.GetString("Url.LiveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hideez.com/404.
        /// </summary>
        internal static string Url_LockVideoTutorial {
            get {
                return ResourceManager.GetString("Url.LockVideoTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hideez.com/404.
        /// </summary>
        internal static string Url_RFIDUsage {
            get {
                return ResourceManager.GetString("Url.RFIDUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hideez.com/404.
        /// </summary>
        internal static string Url_UserManual {
            get {
                return ResourceManager.GetString("Url.UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hideez.com/404.
        /// </summary>
        internal static string Url_VideoTutorial {
            get {
                return ResourceManager.GetString("Url.VideoTutorial", resourceCulture);
            }
        }
    }
}
