//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HideezClient.HideezServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceClientParameters", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ServiceClientParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HideezClient.HideezServiceReference.ClientType ClientTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HideezClient.HideezServiceReference.ClientType ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientType", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    public enum ClientType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceHost = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DesktopClient = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestConsole = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoteDeviceConnection = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class HideezServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceDTO", Namespace="http://schemas.datacontract.org/2004/07/HideezMiddleware.IPC.DTO")]
    [System.SerializableAttribute()]
    public partial class DeviceDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte BatteryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Version BootloaderVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanLockPyProximityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FinishedMainFlowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Version FirmwareVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAuthorizedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBootField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCanUnlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsConnectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInitializedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinPinLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PinAttemptsRemainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ProximityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint StorageFreeSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint StorageTotalSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnlockAttemptsRemainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte Battery {
            get {
                return this.BatteryField;
            }
            set {
                if ((this.BatteryField.Equals(value) != true)) {
                    this.BatteryField = value;
                    this.RaisePropertyChanged("Battery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Version BootloaderVersion {
            get {
                return this.BootloaderVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.BootloaderVersionField, value) != true)) {
                    this.BootloaderVersionField = value;
                    this.RaisePropertyChanged("BootloaderVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanLockPyProximity {
            get {
                return this.CanLockPyProximityField;
            }
            set {
                if ((this.CanLockPyProximityField.Equals(value) != true)) {
                    this.CanLockPyProximityField = value;
                    this.RaisePropertyChanged("CanLockPyProximity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FinishedMainFlow {
            get {
                return this.FinishedMainFlowField;
            }
            set {
                if ((this.FinishedMainFlowField.Equals(value) != true)) {
                    this.FinishedMainFlowField = value;
                    this.RaisePropertyChanged("FinishedMainFlow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Version FirmwareVersion {
            get {
                return this.FirmwareVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmwareVersionField, value) != true)) {
                    this.FirmwareVersionField = value;
                    this.RaisePropertyChanged("FirmwareVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAuthorized {
            get {
                return this.IsAuthorizedField;
            }
            set {
                if ((this.IsAuthorizedField.Equals(value) != true)) {
                    this.IsAuthorizedField = value;
                    this.RaisePropertyChanged("IsAuthorized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBoot {
            get {
                return this.IsBootField;
            }
            set {
                if ((this.IsBootField.Equals(value) != true)) {
                    this.IsBootField = value;
                    this.RaisePropertyChanged("IsBoot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCanUnlock {
            get {
                return this.IsCanUnlockField;
            }
            set {
                if ((this.IsCanUnlockField.Equals(value) != true)) {
                    this.IsCanUnlockField = value;
                    this.RaisePropertyChanged("IsCanUnlock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConnected {
            get {
                return this.IsConnectedField;
            }
            set {
                if ((this.IsConnectedField.Equals(value) != true)) {
                    this.IsConnectedField = value;
                    this.RaisePropertyChanged("IsConnected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInitialized {
            get {
                return this.IsInitializedField;
            }
            set {
                if ((this.IsInitializedField.Equals(value) != true)) {
                    this.IsInitializedField = value;
                    this.RaisePropertyChanged("IsInitialized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinPinLength {
            get {
                return this.MinPinLengthField;
            }
            set {
                if ((this.MinPinLengthField.Equals(value) != true)) {
                    this.MinPinLengthField = value;
                    this.RaisePropertyChanged("MinPinLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerEmail {
            get {
                return this.OwnerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerEmailField, value) != true)) {
                    this.OwnerEmailField = value;
                    this.RaisePropertyChanged("OwnerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PinAttemptsRemain {
            get {
                return this.PinAttemptsRemainField;
            }
            set {
                if ((this.PinAttemptsRemainField.Equals(value) != true)) {
                    this.PinAttemptsRemainField = value;
                    this.RaisePropertyChanged("PinAttemptsRemain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Proximity {
            get {
                return this.ProximityField;
            }
            set {
                if ((this.ProximityField.Equals(value) != true)) {
                    this.ProximityField = value;
                    this.RaisePropertyChanged("Proximity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNo {
            get {
                return this.SerialNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNoField, value) != true)) {
                    this.SerialNoField = value;
                    this.RaisePropertyChanged("SerialNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint StorageFreeSize {
            get {
                return this.StorageFreeSizeField;
            }
            set {
                if ((this.StorageFreeSizeField.Equals(value) != true)) {
                    this.StorageFreeSizeField = value;
                    this.RaisePropertyChanged("StorageFreeSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint StorageTotalSize {
            get {
                return this.StorageTotalSizeField;
            }
            set {
                if ((this.StorageTotalSizeField.Equals(value) != true)) {
                    this.StorageTotalSizeField = value;
                    this.RaisePropertyChanged("StorageTotalSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnlockAttemptsRemain {
            get {
                return this.UnlockAttemptsRemainField;
            }
            set {
                if ((this.UnlockAttemptsRemainField.Equals(value) != true)) {
                    this.UnlockAttemptsRemainField = value;
                    this.RaisePropertyChanged("UnlockAttemptsRemain");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkstationEventDTO", Namespace="http://schemas.datacontract.org/2004/07/HideezMiddleware.IPC.DTO")]
    [System.SerializableAttribute()]
    public partial class WorkstationEventDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeverityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountLogin {
            get {
                return this.AccountLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountLoginField, value) != true)) {
                    this.AccountLoginField = value;
                    this.RaisePropertyChanged("AccountLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProximitySettingsDTO", Namespace="http://schemas.datacontract.org/2004/07/HideezMiddleware.IPC.DTO")]
    [System.SerializableAttribute()]
    public partial class ProximitySettingsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowEditProximitySettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LockProximityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnlockProximityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowEditProximitySettings {
            get {
                return this.AllowEditProximitySettingsField;
            }
            set {
                if ((this.AllowEditProximitySettingsField.Equals(value) != true)) {
                    this.AllowEditProximitySettingsField = value;
                    this.RaisePropertyChanged("AllowEditProximitySettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LockProximity {
            get {
                return this.LockProximityField;
            }
            set {
                if ((this.LockProximityField.Equals(value) != true)) {
                    this.LockProximityField = value;
                    this.RaisePropertyChanged("LockProximity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mac {
            get {
                return this.MacField;
            }
            set {
                if ((object.ReferenceEquals(this.MacField, value) != true)) {
                    this.MacField = value;
                    this.RaisePropertyChanged("Mac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNo {
            get {
                return this.SerialNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNoField, value) != true)) {
                    this.SerialNoField = value;
                    this.RaisePropertyChanged("SerialNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnlockProximity {
            get {
                return this.UnlockProximityField;
            }
            set {
                if ((this.UnlockProximityField.Equals(value) != true)) {
                    this.UnlockProximityField = value;
                    this.RaisePropertyChanged("UnlockProximity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HideezServiceReference.IHideezService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IHideezService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/AttachClient", ReplyAction="http://tempuri.org/IHideezService/AttachClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/AttachClientHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        bool AttachClient(HideezClient.HideezServiceReference.ServiceClientParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/AttachClient", ReplyAction="http://tempuri.org/IHideezService/AttachClientResponse")]
        System.Threading.Tasks.Task<bool> AttachClientAsync(HideezClient.HideezServiceReference.ServiceClientParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/DetachClient", ReplyAction="http://tempuri.org/IHideezService/DetachClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/DetachClientHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void DetachClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/DetachClient", ReplyAction="http://tempuri.org/IHideezService/DetachClientResponse")]
        System.Threading.Tasks.Task DetachClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/Ping", ReplyAction="http://tempuri.org/IHideezService/PingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/PingHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        int Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/Ping", ReplyAction="http://tempuri.org/IHideezService/PingResponse")]
        System.Threading.Tasks.Task<int> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/Shutdown", ReplyAction="http://tempuri.org/IHideezService/ShutdownResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/ShutdownHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void Shutdown();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/Shutdown", ReplyAction="http://tempuri.org/IHideezService/ShutdownResponse")]
        System.Threading.Tasks.Task ShutdownAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetDevices", ReplyAction="http://tempuri.org/IHideezService/GetDevicesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/GetDevicesHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        HideezClient.HideezServiceReference.DeviceDTO[] GetDevices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetDevices", ReplyAction="http://tempuri.org/IHideezService/GetDevicesResponse")]
        System.Threading.Tasks.Task<HideezClient.HideezServiceReference.DeviceDTO[]> GetDevicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetAvailableChannels", ReplyAction="http://tempuri.org/IHideezService/GetAvailableChannelsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/GetAvailableChannelsHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        byte[] GetAvailableChannels(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetAvailableChannels", ReplyAction="http://tempuri.org/IHideezService/GetAvailableChannelsResponse")]
        System.Threading.Tasks.Task<byte[]> GetAvailableChannelsAsync(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/DisconnectDevice", ReplyAction="http://tempuri.org/IHideezService/DisconnectDeviceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/DisconnectDeviceHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void DisconnectDevice(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/DisconnectDevice", ReplyAction="http://tempuri.org/IHideezService/DisconnectDeviceResponse")]
        System.Threading.Tasks.Task DisconnectDeviceAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoveDevice", ReplyAction="http://tempuri.org/IHideezService/RemoveDeviceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/RemoveDeviceHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void RemoveDevice(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoveDevice", ReplyAction="http://tempuri.org/IHideezService/RemoveDeviceResponse")]
        System.Threading.Tasks.Task RemoveDeviceAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/EstablishRemoteDeviceConnection", ReplyAction="http://tempuri.org/IHideezService/EstablishRemoteDeviceConnectionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/EstablishRemoteDeviceConnectionHideezServiceFau" +
            "ltFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        string EstablishRemoteDeviceConnection(string serialNo, byte channelNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/EstablishRemoteDeviceConnection", ReplyAction="http://tempuri.org/IHideezService/EstablishRemoteDeviceConnectionResponse")]
        System.Threading.Tasks.Task<string> EstablishRemoteDeviceConnectionAsync(string serialNo, byte channelNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_VerifyCommand", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_VerifyCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/RemoteConnection_VerifyCommandHideezServiceFaul" +
            "tFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        byte[] RemoteConnection_VerifyCommand(string connectionId, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_VerifyCommand", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_VerifyCommandResponse")]
        System.Threading.Tasks.Task<byte[]> RemoteConnection_VerifyCommandAsync(string connectionId, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_RemoteCommand", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_RemoteCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/RemoteConnection_RemoteCommandHideezServiceFaul" +
            "tFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        byte[] RemoteConnection_RemoteCommand(string connectionId, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_RemoteCommand", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_RemoteCommandResponse")]
        System.Threading.Tasks.Task<byte[]> RemoteConnection_RemoteCommandAsync(string connectionId, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_ResetChannel", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_ResetChannelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/RemoteConnection_ResetChannelHideezServiceFault" +
            "Fault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void RemoteConnection_ResetChannel(string connectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/RemoteConnection_ResetChannel", ReplyAction="http://tempuri.org/IHideezService/RemoteConnection_ResetChannelResponse")]
        System.Threading.Tasks.Task RemoteConnection_ResetChannelAsync(string connectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/PublishEvent", ReplyAction="http://tempuri.org/IHideezService/PublishEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/PublishEventHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void PublishEvent(HideezClient.HideezServiceReference.WorkstationEventDTO workstationEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/PublishEvent", ReplyAction="http://tempuri.org/IHideezService/PublishEventResponse")]
        System.Threading.Tasks.Task PublishEventAsync(HideezClient.HideezServiceReference.WorkstationEventDTO workstationEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SendPin", ReplyAction="http://tempuri.org/IHideezService/SendPinResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/SendPinHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void SendPin(string deviceId, byte[] pin, byte[] oldPin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SendPin", ReplyAction="http://tempuri.org/IHideezService/SendPinResponse")]
        System.Threading.Tasks.Task SendPinAsync(string deviceId, byte[] pin, byte[] oldPin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/CancelPin", ReplyAction="http://tempuri.org/IHideezService/CancelPinResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/CancelPinHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void CancelPin(string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/CancelPin", ReplyAction="http://tempuri.org/IHideezService/CancelPinResponse")]
        System.Threading.Tasks.Task CancelPinAsync(string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SendActivationCode", ReplyAction="http://tempuri.org/IHideezService/SendActivationCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/SendActivationCodeHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void SendActivationCode(string deviceId, byte[] activationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SendActivationCode", ReplyAction="http://tempuri.org/IHideezService/SendActivationCodeResponse")]
        System.Threading.Tasks.Task SendActivationCodeAsync(string deviceId, byte[] activationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/CancelActivationCode", ReplyAction="http://tempuri.org/IHideezService/CancelActivationCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/CancelActivationCodeHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void CancelActivationCode(string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/CancelActivationCode", ReplyAction="http://tempuri.org/IHideezService/CancelActivationCodeResponse")]
        System.Threading.Tasks.Task CancelActivationCodeAsync(string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SetProximitySettings", ReplyAction="http://tempuri.org/IHideezService/SetProximitySettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/SetProximitySettingsHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void SetProximitySettings(string mac, int lockProximity, int unlockProximity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SetProximitySettings", ReplyAction="http://tempuri.org/IHideezService/SetProximitySettingsResponse")]
        System.Threading.Tasks.Task SetProximitySettingsAsync(string mac, int lockProximity, int unlockProximity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetCurrentProximitySettings", ReplyAction="http://tempuri.org/IHideezService/GetCurrentProximitySettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/GetCurrentProximitySettingsHideezServiceFaultFa" +
            "ult", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        HideezClient.HideezServiceReference.ProximitySettingsDTO GetCurrentProximitySettings(string mac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetCurrentProximitySettings", ReplyAction="http://tempuri.org/IHideezService/GetCurrentProximitySettingsResponse")]
        System.Threading.Tasks.Task<HideezClient.HideezServiceReference.ProximitySettingsDTO> GetCurrentProximitySettingsAsync(string mac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetServerAddress", ReplyAction="http://tempuri.org/IHideezService/GetServerAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/GetServerAddressHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        string GetServerAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/GetServerAddress", ReplyAction="http://tempuri.org/IHideezService/GetServerAddressResponse")]
        System.Threading.Tasks.Task<string> GetServerAddressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/ChangeServerAddress", ReplyAction="http://tempuri.org/IHideezService/ChangeServerAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/ChangeServerAddressHideezServiceFaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        bool ChangeServerAddress(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/ChangeServerAddress", ReplyAction="http://tempuri.org/IHideezService/ChangeServerAddressResponse")]
        System.Threading.Tasks.Task<bool> ChangeServerAddressAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/IsSoftwareVaultUnlockModuleEnabled", ReplyAction="http://tempuri.org/IHideezService/IsSoftwareVaultUnlockModuleEnabledResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/IsSoftwareVaultUnlockModuleEnabledHideezService" +
            "FaultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        bool IsSoftwareVaultUnlockModuleEnabled();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/IsSoftwareVaultUnlockModuleEnabled", ReplyAction="http://tempuri.org/IHideezService/IsSoftwareVaultUnlockModuleEnabledResponse")]
        System.Threading.Tasks.Task<bool> IsSoftwareVaultUnlockModuleEnabledAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SetSoftwareVaultUnlockModuleState", ReplyAction="http://tempuri.org/IHideezService/SetSoftwareVaultUnlockModuleStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HideezClient.HideezServiceReference.HideezServiceFault), Action="http://tempuri.org/IHideezService/SetSoftwareVaultUnlockModuleStateHideezServiceF" +
            "aultFault", Name="HideezServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
        void SetSoftwareVaultUnlockModuleState(bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHideezService/SetSoftwareVaultUnlockModuleState", ReplyAction="http://tempuri.org/IHideezService/SetSoftwareVaultUnlockModuleStateResponse")]
        System.Threading.Tasks.Task SetSoftwareVaultUnlockModuleStateAsync(bool enabled);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHideezServiceChannel : HideezClient.HideezServiceReference.IHideezService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HideezServiceClient : System.ServiceModel.ClientBase<HideezClient.HideezServiceReference.IHideezService>, HideezClient.HideezServiceReference.IHideezService {
        
        public HideezServiceClient() {
        }
        
        public HideezServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HideezServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HideezServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HideezServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AttachClient(HideezClient.HideezServiceReference.ServiceClientParameters parameters) {
            return base.Channel.AttachClient(parameters);
        }
        
        public System.Threading.Tasks.Task<bool> AttachClientAsync(HideezClient.HideezServiceReference.ServiceClientParameters parameters) {
            return base.Channel.AttachClientAsync(parameters);
        }
        
        public void DetachClient() {
            base.Channel.DetachClient();
        }
        
        public System.Threading.Tasks.Task DetachClientAsync() {
            return base.Channel.DetachClientAsync();
        }
        
        public int Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<int> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public void Shutdown() {
            base.Channel.Shutdown();
        }
        
        public System.Threading.Tasks.Task ShutdownAsync() {
            return base.Channel.ShutdownAsync();
        }
        
        public HideezClient.HideezServiceReference.DeviceDTO[] GetDevices() {
            return base.Channel.GetDevices();
        }
        
        public System.Threading.Tasks.Task<HideezClient.HideezServiceReference.DeviceDTO[]> GetDevicesAsync() {
            return base.Channel.GetDevicesAsync();
        }
        
        public byte[] GetAvailableChannels(string serialNo) {
            return base.Channel.GetAvailableChannels(serialNo);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetAvailableChannelsAsync(string serialNo) {
            return base.Channel.GetAvailableChannelsAsync(serialNo);
        }
        
        public void DisconnectDevice(string id) {
            base.Channel.DisconnectDevice(id);
        }
        
        public System.Threading.Tasks.Task DisconnectDeviceAsync(string id) {
            return base.Channel.DisconnectDeviceAsync(id);
        }
        
        public void RemoveDevice(string id) {
            base.Channel.RemoveDevice(id);
        }
        
        public System.Threading.Tasks.Task RemoveDeviceAsync(string id) {
            return base.Channel.RemoveDeviceAsync(id);
        }
        
        public string EstablishRemoteDeviceConnection(string serialNo, byte channelNo) {
            return base.Channel.EstablishRemoteDeviceConnection(serialNo, channelNo);
        }
        
        public System.Threading.Tasks.Task<string> EstablishRemoteDeviceConnectionAsync(string serialNo, byte channelNo) {
            return base.Channel.EstablishRemoteDeviceConnectionAsync(serialNo, channelNo);
        }
        
        public byte[] RemoteConnection_VerifyCommand(string connectionId, byte[] data) {
            return base.Channel.RemoteConnection_VerifyCommand(connectionId, data);
        }
        
        public System.Threading.Tasks.Task<byte[]> RemoteConnection_VerifyCommandAsync(string connectionId, byte[] data) {
            return base.Channel.RemoteConnection_VerifyCommandAsync(connectionId, data);
        }
        
        public byte[] RemoteConnection_RemoteCommand(string connectionId, byte[] data) {
            return base.Channel.RemoteConnection_RemoteCommand(connectionId, data);
        }
        
        public System.Threading.Tasks.Task<byte[]> RemoteConnection_RemoteCommandAsync(string connectionId, byte[] data) {
            return base.Channel.RemoteConnection_RemoteCommandAsync(connectionId, data);
        }
        
        public void RemoteConnection_ResetChannel(string connectionId) {
            base.Channel.RemoteConnection_ResetChannel(connectionId);
        }
        
        public System.Threading.Tasks.Task RemoteConnection_ResetChannelAsync(string connectionId) {
            return base.Channel.RemoteConnection_ResetChannelAsync(connectionId);
        }
        
        public void PublishEvent(HideezClient.HideezServiceReference.WorkstationEventDTO workstationEvent) {
            base.Channel.PublishEvent(workstationEvent);
        }
        
        public System.Threading.Tasks.Task PublishEventAsync(HideezClient.HideezServiceReference.WorkstationEventDTO workstationEvent) {
            return base.Channel.PublishEventAsync(workstationEvent);
        }
        
        public void SendPin(string deviceId, byte[] pin, byte[] oldPin) {
            base.Channel.SendPin(deviceId, pin, oldPin);
        }
        
        public System.Threading.Tasks.Task SendPinAsync(string deviceId, byte[] pin, byte[] oldPin) {
            return base.Channel.SendPinAsync(deviceId, pin, oldPin);
        }
        
        public void CancelPin(string deviceId) {
            base.Channel.CancelPin(deviceId);
        }
        
        public System.Threading.Tasks.Task CancelPinAsync(string deviceId) {
            return base.Channel.CancelPinAsync(deviceId);
        }
        
        public void SendActivationCode(string deviceId, byte[] activationCode) {
            base.Channel.SendActivationCode(deviceId, activationCode);
        }
        
        public System.Threading.Tasks.Task SendActivationCodeAsync(string deviceId, byte[] activationCode) {
            return base.Channel.SendActivationCodeAsync(deviceId, activationCode);
        }
        
        public void CancelActivationCode(string deviceId) {
            base.Channel.CancelActivationCode(deviceId);
        }
        
        public System.Threading.Tasks.Task CancelActivationCodeAsync(string deviceId) {
            return base.Channel.CancelActivationCodeAsync(deviceId);
        }
        
        public void SetProximitySettings(string mac, int lockProximity, int unlockProximity) {
            base.Channel.SetProximitySettings(mac, lockProximity, unlockProximity);
        }
        
        public System.Threading.Tasks.Task SetProximitySettingsAsync(string mac, int lockProximity, int unlockProximity) {
            return base.Channel.SetProximitySettingsAsync(mac, lockProximity, unlockProximity);
        }
        
        public HideezClient.HideezServiceReference.ProximitySettingsDTO GetCurrentProximitySettings(string mac) {
            return base.Channel.GetCurrentProximitySettings(mac);
        }
        
        public System.Threading.Tasks.Task<HideezClient.HideezServiceReference.ProximitySettingsDTO> GetCurrentProximitySettingsAsync(string mac) {
            return base.Channel.GetCurrentProximitySettingsAsync(mac);
        }
        
        public string GetServerAddress() {
            return base.Channel.GetServerAddress();
        }
        
        public System.Threading.Tasks.Task<string> GetServerAddressAsync() {
            return base.Channel.GetServerAddressAsync();
        }
        
        public bool ChangeServerAddress(string address) {
            return base.Channel.ChangeServerAddress(address);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeServerAddressAsync(string address) {
            return base.Channel.ChangeServerAddressAsync(address);
        }
        
        public bool IsSoftwareVaultUnlockModuleEnabled() {
            return base.Channel.IsSoftwareVaultUnlockModuleEnabled();
        }
        
        public System.Threading.Tasks.Task<bool> IsSoftwareVaultUnlockModuleEnabledAsync() {
            return base.Channel.IsSoftwareVaultUnlockModuleEnabledAsync();
        }
        
        public void SetSoftwareVaultUnlockModuleState(bool enabled) {
            base.Channel.SetSoftwareVaultUnlockModuleState(enabled);
        }
        
        public System.Threading.Tasks.Task SetSoftwareVaultUnlockModuleStateAsync(bool enabled) {
            return base.Channel.SetSoftwareVaultUnlockModuleStateAsync(enabled);
        }
    }
}
